# Generated by Django 4.2.1 on 2023-06-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plannings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planning",
            name="name",
            field=models.TextField(blank=True),
        ),
    ]
