# Generated by Django 4.2.1 on 2023-06-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plannings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
                ("activities", models.CharField(default="PTO", max_length=2000)),
                ("pto", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
